### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by lukeisontheroad** [MrColdbird/android_kernel_oukitel_k4000pro#1]

**Comment by MrColdbird** [comment]
No its not. I'm just having my hands full with a few other things right now.
That's the same reason as to why the ZUK Z1 buildbot is currently defunct.

If you absolutely need to know, I've been busy with a big job assignment and me and my wife moving to a new place.

**Comment by janengelmohr** [comment]
Good luck with that then!

**Comment by lukeisontheroad** [comment]
Thanks for the information, good luck 👍
